version: "3.3"

networks:
  common_network:
volumes:
  qtumd_mainnet_volume:

services:
  janus_testnet:
    env_file:
      - ../.env
    image: ipetrov22/janus:latest
    container_name: janus_testnet
    build:
      context: ../../
      cache_from:
        - golang:1.18-alpine
    ports:
      - "23889:23889"
    environment:
      - QTUM_RPC=${TEST_RPC_URL}
      - COMPOSE_PROJECT_NAME=mainnet
    volumes:
      - ../standalone/myaccounts.txt:$GOPATH/janus/myaccounts.txt
      - ../../https:/https
      - ../../logs:/logs
    # depends_on:
    #   - qtum_mainnet
    command: --bind 0.0.0.0 --port 23889 --ignoreTransactions --accounts $GOPATH/janus/myaccounts.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - common_network

